---
parameters:
  - name: action
    type: string
    values:
      - Default
      - DryRun
  - name: gitUserEmail
    type: string
  - name: gitUserName
    type: string
  - name: organisationName
    type: string
  - name: rangerVersion
    type: string

resources:
  repositories:
    - repository: self

jobs:
  - job: Execute
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InstallRangerCLI@0
        inputs:
          version: ${{ parameters.rangerVersion }}
      - task: DeploySet@0
        inputs:
          gitUserEmail: ${{ parameters.gitUserEmail }}
          gitUserName: ${{ parameters.gitUserName }}
          organisationName: frontierdigital
          pat: $(System.AccessToken)
          projectName: $(System.TeamProject)
      - task: PromoteSet@0
        inputs:
          gitUserEmail: ${{ parameters.gitUserEmail }}
          gitUserName: ${{ parameters.gitUserName }}
          organisationName: ${{ parameters.organisationName }}
          pat: $(System.AccessToken)
          projectName: $(System.TeamProject)
