---
parameters:
  - name: configRef
    type: string
  - name: destroySteps
    type: stepList
    default: []
  - name: environment
    type: string
  - name: installSteps
    type: stepList
    default: []
  - name: organisationName
    type: string
  - name: pool
    type: object
  - name: serviceConnectionName
    type: string
  - name: timeoutInMinutes
    type: number
    default: 60
  - name: workloadFeedName
    type: string

resources:
  repositories:
    - repository: self

stages:
  - template: ../stages/destroy.yml
    parameters:
      configRef: ${{ parameters.configRef }}
      destroySteps: ${{ parameters.destroySteps }}
      environment: ${{ parameters.environment }}
      installSteps: ${{ parameters.installSteps }}
      organisationName: ${{ parameters.organisationName }}
      pool: ${{ parameters.pool }}
      serviceConnectionName: ${{ parameters.serviceConnectionName }}
      timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
      workloadFeedName: ${{ parameters.workloadFeedName }}
