---
parameters:
  - name: action
    type: string
    values:
      - Default
      - Publish
  - name: buildSteps
    type: stepList
    default: []
  - name: installSteps
    type: stepList
    default: []
  - name: pool
    type: object
    default:
      vmImage: ubuntu-latest
  - name: postPublishSteps
    type: stepList
    default: []
  - name: prePublishSteps
    type: stepList
    default: []
  - name: testSteps
    type: stepList
    default: []
  - name: workloadFeedName
    type: string

resources:
  repositories:
    - repository: self

stages:
  - template: ../stages/build.yml
    parameters:
      buildSteps: ${{ parameters.buildSteps }}
      installSteps: ${{ parameters.installSteps }}
      pool: ${{ parameters.pool }}
      postPublishSteps: ${{ parameters.postPublishSteps }}
      prePublishSteps: ${{ parameters.prePublishSteps }}
      testSteps: ${{ parameters.testSteps }}
  - template: ../stages/publish.yml
    parameters:
      condition: |
        and(
          succeeded(),
          or(
            eq(variables['build.sourceBranch'], 'refs/heads/main'),
            eq('${{ parameters.action }}', 'Publish')
          )
        )
      jobs:
        - template: ../jobs/publish-workload-package.yml
          parameters:
            workloadFeedName: ${{ parameters.workloadFeedName }}
      pool: ${{ parameters.pool }}
