---
parameters:
  - name: configRef
    type: string
  - name: deploySteps
    type: stepList
    default: []
  - name: environment
    type: string
  - name: installSteps
    type: stepList
    default: []
  - name: organisationName
    type: string
  - name: planSteps
    type: stepList
    default: []
  - name: serviceConnectionName
    type: string
  - name: workloadFeedName
    type: string

resources:
  repositories:
    - repository: self

stages:
  - ${{ if ne(parameters.planSteps, '') }}:
    - template: ../stages/deploy.yml
      parameters:
        configRef: ${{ parameters.configRef }}
        deploySteps: ${{ parameters.planSteps }}
        environment: ${{ parameters.environment }}
        installSteps: ${{ parameters.installSteps }}
        organisationName: ${{ parameters.organisationName }}
        serviceConnectionName: ${{ parameters.serviceConnectionName }}
        workloadFeedName: ${{ parameters.workloadFeedName }}
    - template: ../stages/deploy.yml
      parameters:
        configRef: ${{ parameters.configRef }}
        deploySteps: ${{ parameters.deploySteps }}
        environment: ${{ parameters.environment }}
        installSteps: ${{ parameters.installSteps }}
        organisationName: ${{ parameters.organisationName }}
        serviceConnectionName: ${{ parameters.serviceConnectionName }}
        workloadFeedName: ${{ parameters.workloadFeedName }}
