---
parameters:
  - name: buildSteps
    type: stepList
    default: []
  - name: installSteps
    type: stepList
    default: []
  - name: pool
    type: object
  - name: postPublishSteps
    type: stepList
    default: []
  - name: prePublishSteps
    type: stepList
    default: []
  - name: testSteps
    type: stepList
    default: []
  - name: timeoutInMinutes
    type: number
    default: 60

stages:
  - stage: Build
    pool: ${{ parameters.pool }}
    jobs:
      - template: ../jobs/preflight.yml
      - job: Build
        dependsOn: Preflight
        variables:
          - name: versionFromFile
            value: $[dependencies.Preflight.outputs['getVersionFromFile.versionFromFile']]
          - name: versionLabel
            ${{ if or(eq(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.SourceBranchName'], 'master')) }}:
              value: ""
            ${{ if and(ne(variables['Build.SourceBranchName'], 'main'), ne(variables['Build.SourceBranchName'], 'master')) }}:
              value: "-unstable"
          - name: pipelineCounter
            value: $[counter(dependencies.Preflight.outputs['getVersionFromFile.versionFromFile'], 0)]
        steps:
          - checkout: self
            submodules: true
          - template: ../steps/set-version-variable.yml
            parameters:
              pipelineCounter: $(pipelineCounter)
              versionFromFile: $(versionFromFile)
              versionLabel: $(versionLabel)
          - template: ../steps/update-version-file.yml
            parameters:
              version: $(version)
          - ${{ parameters.installSteps }}
          - ${{ parameters.buildSteps }}
          - ${{ parameters.testSteps }}
          - ${{ parameters.prePublishSteps }}
          - template: ../steps/add-tag.yml
            parameters:
              force: true # TODO: Remove
              tag: $(version)
          - template: ../steps/publish-pipeline-artifact.yml
          - ${{ parameters.postPublishSteps }}
