---
parameters:
  - name: configRef
    type: string
  - name: deploySteps
    type: stepList
    default: []
  - name: environment
    type: string
  - name: installSteps
    type: stepList
    default: []
  - name: organisationName
    type: string
  - name: serviceConnectionName
    type: string
  - name: set
    type: string
  - name: workloadFeedName
    type: string
  - name: workloadName
    type: string

stages:
  - stage: Deploy
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: DeployFromPipelineArtifact
        displayName: Deploy workload package
        environment:
          name: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - checkout: none
                - template: ../steps/clear-default-working-directory.yml
                - template: ../steps/download-workload-package.yml
                  parameters:
                    feedName: ${{ parameters.workloadFeedName }}
                    version: $(Build.SourceBranchName)
                - template: ../steps/configure-git-authentication.yml
                  parameters:
                    organisationName: ${{ parameters.organisationName }}
                    pat: $(System.AccessToken)
                - ${{ if not(eq(parameters.configRef, 'null')) }}:
                    - template: ../steps/fetch-config-and-secrets.yml
                      parameters:
                        organisationName: ${{ parameters.organisationName }}
                        ref: ${{ parameters.configRef }}
                        serviceConnectionName: ${{ parameters.serviceConnectionName }}
                - ${{ parameters.installSteps }}
                - ${{ parameters.deploySteps }}
                - template: ../steps/clear-agent-build-directory.yml
