---
parameters:
  - name: condition
    type: string
  - name: jobs
    type: jobList
  - name: pool
    type: object
    default:
      vmImage: ubuntu-latest

stages:
  - stage: Publish
    pool: ${{ parameters.pool }}
    condition: ${{ parameters.condition }}
    jobs:
      - ${{ parameters.jobs }}
